#!/bin/bash

# ----------------------------------------------

# random functions area

function check_error {
	if [ $? -ne 0 ]
	then
		echo $1
		exit 1
	fi
}

# ----------------------------------------------

# variable declaration area

TESTFD=./tests

EXEC_LEX=clex
EXEC_YACC=cyacc

# ----------------------------------------------

echo "----------------------------------------"
echo "PUC-Rio / Compiladores / Linguagem Monga" 
echo "Julio Ribeiro da Silva - 0911409" 
echo "----------------------------------------"
echo 

# ----------------------------------------------

# compiling sources for tests 

make
check_error "ERROR!"
echo 
# ----------------------------------------------

# testing lex

for FILE in $TESTFD/*.in
do
	F=`basename $FILE .in`
	./$EXEC_LEX <"$TESTFD/$F.in" >"$TESTFD/test.out"

	echo -n "Testing lex ($FILE)... "
	diff "$TESTFD/test.out" "$TESTFD/$F.gab" >diff.err
	check_error "ERROR!"
	echo "OK!"

	rm "$TESTFD/test.out"
done
echo

rm -f diff.err

# ----------------------------------------------

# testing yacc

for FILE in $TESTFD/*.in
do
	echo -n "Testing yacc ($FILE)... "
	./$EXEC_YACC <$FILE 1>/dev/null 2>yacc.err
	check_error "ERROR!"
	echo "OK!"
done
echo

rm yacc.err

# ----------------------------------------------

